# Generated by Django 3.2.5 on 2021-07-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_type_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(default='', max_length=7),
        ),
    ]
