# Generated by Django 3.2.5 on 2021-07-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_type_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField(null=True, unique=True)),
                ('reg', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='region',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='regen',
            field=models.ManyToManyField(to='pokemon.ReGen'),
        ),
    ]
