# Generated by Django 3.2.5 on 2021-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20210727_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='regen',
            field=models.ManyToManyField(to='pokemon.Regen'),
        ),
    ]
